
default: &default
  adapter: postgresql
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  timeout: 5000

development:
  <<: *default
  database: funzoapp_db_development


test:
  <<: *default
  database: funzoapp_db_test

production:
  <<: *default
  database: funzoapp_db_production
